### ISSUE TITLE
Node or Angular library?

### ISSUE THREAD

**Issue by jrforrest** [jbhurley92/leagueoflegends#1]
Hey!

Last we talked I thought you were building a Node wrapper to make the API calls, but now I'm noticing that your calls are being made from an Angular service with the `$http` provider.

Do you intend to begin with the API calls being made directly from Angular and then transition to a Node BE later?

**Comment by jbhurley92** [comment]
Yeah I going to try and just get the calls working cause I underestimated
this API. Could you take a look again and tell me how to set up my promise
in my factory for my function summonerByName. But yeah I am trying to do
what I can since I have 8 days left.

**Comment by jrforrest** [comment]
Those functions should be anonymous I think.

**Comment by jrforrest** [comment]
It will help a lot if you format your code properly, it's really hard to read currently.

**Comment by jbhurley92** [comment]
Yeah they should be, but I have a lot left to do in a short time pretty
much 6 days cause the last 2 days we arent supposed to code.
